/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XsalgovicPatientCard {
        "apiBase": string;
    }
}
declare global {
    interface HTMLXsalgovicPatientCardElement extends Components.XsalgovicPatientCard, HTMLStencilElement {
    }
    var HTMLXsalgovicPatientCardElement: {
        prototype: HTMLXsalgovicPatientCardElement;
        new (): HTMLXsalgovicPatientCardElement;
    };
    interface HTMLElementTagNameMap {
        "xsalgovic-patient-card": HTMLXsalgovicPatientCardElement;
    }
}
declare namespace LocalJSX {
    interface XsalgovicPatientCard {
        "apiBase"?: string;
    }
    interface IntrinsicElements {
        "xsalgovic-patient-card": XsalgovicPatientCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xsalgovic-patient-card": LocalJSX.XsalgovicPatientCard & JSXBase.HTMLAttributes<HTMLXsalgovicPatientCardElement>;
        }
    }
}
